### ISSUE TITLE
[Feature Request] Dark Mode

### ISSUE THREAD

**Issue by christianhacker** [allegroai/clearml-web#26]
Quick question: is there any plan to implement a "global" dark mode for the web UI?

The closest I can get is a browser addon plus using themes/templates in any plots I report, but this doesn't affect plots that are auto-magically generated.

Thanks

**Comment by ainoam** [comment]
@christianhacker Thanks for posting this feature request: A completely "Dark" UI is on our TODO list, but it's quite far out on ClearML's roadmap.
