### ISSUE TITLE
[Bug] User filter not populated when navigating directly

### ISSUE THREAD

**Issue by fellhorn** [allegroai/clearml-web#33]
## Issue

The user filter is not populated when one navigates directly to the tabular experiments view instead of clicking through from the root level experiments page.

![image](https://user-images.githubusercontent.com/26092524/183382078-747d555b-1f01-4b47-885c-3473f18009b4.png)

## Steps to reproduce

Navigate to `https://[clearML server]/projects/*/experiments`, the user filter should be empty. When going to `https://[clearML server]/projects` instead and then clicking on `All experiments` it is populated though.

## Further details

In the network tab of devtools I saw that in both cases `users.get_all_ex` is called. Thus maybe it is just a timing issue that the table is rendered and not updated when the user state is finally populated.

**Comment by ainoam** [comment]
Thanks for noticing @fellhorn. We'll take a look.

**Comment by pollfly** [comment]
Hey @fellhorn ! Just letting you know that this issue has been resolved in clearml-server [v.1.8.0](https://github.com/allegroai/clearml-server/releases/tag/v1.8.0). Let us know if there are any issues :)

**Comment by fellhorn** [comment]
> Hey @fellhorn ! Just letting you know that this issue has been resolved in clearml-server [v.1.8.0](https://github.com/allegroai/clearml-server/releases/tag/v1.8.0). Let us know if there are any issues :)

Fantastic! Thanks a lot :)
