### ISSUE TITLE
Default pipeline without local debugging fails to start

### ISSUE THREAD

**Issue by freddessert** [allegroai/clearml-web#36]
Hello,
When trying to run the example [here](https://github.com/allegroai/clearml-web/blob/master/src/app/webapp-common/pipelines/pipelines-page/pipelines-page.component.ts#L28) with `PipelineDecorator.run_locally()` commented *out* I run into the following error:
```
File "/usr/local/lib/python3.8/dist-packages/clearml-1.7.2-py3.8.egg/clearml/task.py", line 1282, in enqueue
    raise ValueError('Could not find queue named "{}"'.format(queue_name))
ValueError: Could not find queue named "services"
```

Thank you!

**Comment by freddessert** [comment]
I am running a locally deployed open-source server @jkhenning. The SDK sets the default value of the executing pipeline queue to be `services`.

**Comment by jkhenning** [comment]
In the default open-source server deployment (docker-compose) there's a services agent, but you need to provide it with the `CLEARML_API_ACCESS_KEY` and `CLEARML_API_SECRET_KEY` environment variables so it can connect to the server. This agent is designed to automatically create the `services` queue and start monitoring it.

**Comment by freddessert** [comment]
I think that makese sense, I am just not entirely sure how I am supposed to option the `CLEARML_API_ACCESS_KEY` and `CLEARML_API_SECRET_KEY` prior to the server deployment? But also, if I change the queue name to `default` it will work just fine, the `services` queue simply does not exist at the time I ran it.

**Comment by jkhenning** [comment]
Well, you can actually start the server, create the credentials, spin down the docker-compose, add the env vars and start it up again. We're working on improving that in future versions so you won't have to do that.

We'll take a look at the PR 🙂
