### ISSUE TITLE
pipeline dead link

### ISSUE THREAD

**Issue by MSutt** [allegroai/clearml-web#40]
The link to the doc `https://clear.ml/docs/latest/docs/pipelines/pipelines/` is dead.
https://github.com/allegroai/clearml-web/blob/9f8f256186169a839d28b34d2c559dc1f9e8e9ef/src/app/webapp-common/pipelines/pipelines-page/pipelines-page.component.html#L51

It should be `https://clear.ml/docs/latest/docs/pipelines/` instead

**Comment by qwaxys** [comment]
Fixing this in pull request #41
