### ISSUE TITLE
Wrong URI in debug samples when using custom S3 bucket

### ISSUE THREAD

**Issue by galatolofederico** [allegroai/clearml-web#46]
When using a custom S3 bucket, such as minio, the UI is not using the correct URI for the debug sample resources.

The following error message appears in the console: `Unable to parse "https//s3.mydomain.xyz" as a whatwg URL` and `ERROR EndpointError: Custom endpoint https//s3.mydomain.xyz was not a valid URI`. The UI shows `Unable to load image`.

This bug appears in version `1.8.0`. Version `1.7.0` is not affected by the bug.
Version `1.9.1` and `1.9.1-312` are affected by the bug.

**Comment by ainoam** [comment]
Thanks for reporting @galatolofederico.
A fix version should be coming out in the next few days.

**Comment by pollfly** [comment]
Hey @galatolofederico! Just letting you know that this issue has been resolved in the recently released clearml-server [v1.9.2](https://github.com/allegroai/clearml-server/releases/tag/v1.9.2). Let us know if there are any issues :)

**Comment by galatolofederico** [comment]
Thanks for your work! I will update my instance in a few days and i will let you know if everything is ok
